name: movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    dio: ^5.4.1
    flutter:
        sdk: flutter
    retrofit: ">=4.0.0 <5.0.0"
    logger: any #for logging purpose
    json_annotation: ^4.8.1
    google_fonts:
    skeletonizer: ^1.1.0
    carousel_slider: ^4.2.1
    number_paginator: ^0.4.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    retrofit_generator: ">=7.0.0 <8.0.0"
    build_runner: ">=2.3.0 <4.0.0"

flutter:
    uses-material-design: true
    assets:
        - lib/images/
